<?php

define( "YOUTUBE_IMPORTER_SECONDLINE_NAME", 'Auto YouTube Importer' );
define( "YOUTUBE_IMPORTER_SECONDLINE_NAME_SHORT", 'YouTube Importer' );
define( "YOUTUBE_IMPORTER_SECONDLINE_ALIAS", 'youtube_importer_secondline' );
define( "YOUTUBE_IMPORTER_SECONDLINE_PREFIX", 'youtube-importer-secondline' );

define( "YOUTUBE_IMPORTER_SECONDLINE_SETTINGS_PERMISSION_CAP", 'manage_options' );
define( "YOUTUBE_IMPORTER_SECONDLINE_FEED_PERMISSION_CAP", 'manage_options' );
define( "YOUTUBE_IMPORTER_SECONDLINE_REST_API_PREFIX", YOUTUBE_IMPORTER_SECONDLINE_PREFIX );
define( 'YOUTUBE_IMPORTER_SECONDLINE_LANGUAGE_DIRECTORY', basename( dirname( YOUTUBE_IMPORTER_SECONDLINE_BASE_FILE_PATH ) ) . '/languages/'  );

define( "YOUTUBE_IMPORTER_SECONDLINE_POST_TYPE_IMPORT", 'secondline_import_yt' );